name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          
      - name: Install dependencies
        run: pnpm install
        
      - name: Build
        run: pnpm build
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
```

## 4. configurar GitHub Pages

1. Sube tu código a GitHub
2. Ve a tu repositorio → **Settings** → **Pages**
3. En "Source", selecciona **GitHub Actions**

## 5. eliminar de Vercel

Una vez que GitHub Pages esté funcionando:

1. Ve a tu proyecto en Vercel
2. Settings → General → Delete Project

## 6. configurar el dominio en Cloudflare

Ahora en Cloudflare:

1. Ve a DNS
2. Cambia el registro que apunta a Vercel por uno que apunte a GitHub Pages:
```
Type: CNAME
Name: paideiahosting (o @)
Content: TU-USUARIO.github.io
Proxy: ✅ Proxied (naranja)